version: '2.1'

services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: $PG_URI
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://0.0.0.0:3000/
volumes:
    pgdata: {}
